/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    IconAdd: typeof import('~icons/icon/add')['default']
    IconAddUser: typeof import('~icons/icon/add-user')['default']
    IconAnnouncement: typeof import('~icons/icon/announcement')['default']
    IconBrush: typeof import('~icons/icon/brush')['default']
    IconCancel: typeof import('~icons/icon/cancel')['default']
    IconChat: typeof import('~icons/icon/chat')['default']
    IconClip: typeof import('~icons/icon/clip')['default']
    IconClipboard: typeof import('~icons/icon/clipboard')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconCross: typeof import('~icons/icon/cross')['default']
    IconCrossWithCircle: typeof import('~icons/icon/cross-with-circle')['default']
    IconDelete: typeof import('~icons/icon/delete')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconEdit: typeof import('~icons/icon/edit')['default']
    IconEllipse: typeof import('~icons/icon/ellipse')['default']
    IconFile: typeof import('~icons/icon/file')['default']
    IconLeftArrow: typeof import('~icons/icon/left-arrow')['default']
    IconLeftUpArrow: typeof import('~icons/icon/left-up-arrow')['default']
    IconPen: typeof import('~icons/icon/pen')['default']
    IconPhoto: typeof import('~icons/icon/photo')['default']
    IconReturn: typeof import('~icons/icon/return')['default']
    IconRightArrow: typeof import('~icons/icon/right-arrow')['default']
    IconSave: typeof import('~icons/icon/save')['default']
    IconSend: typeof import('~icons/icon/send')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
